name: Push gcr.io/soluble-oss/kubetap-mitmproxy
on:
  # rebuild and push the container, updating dependencies, every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [master]
#    paths:
#    - 'proxies/mitmproxy'

jobs:
  kubetap-mitmproxy:
    timeout-minutes: 5
    name: Build and push mitmproxy to GCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Push to GCR
        uses: docker/build-push-action@v6
        with:
          context: ./proxies/mitmproxy
          push: true
          tags: ghcr.io/${{ github.repository }}/kubetap-mitmproxy:latest

